---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: book-install
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./bookinfo/install
  prune: false
  sourceRef:
    kind: GitRepository
    name: deploymentrepo
  targetNamespace: bookinfo

