---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tsbmp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./tsbcp
      sourceRef:
        kind: GitRepository
        name: deploymentrepo
  interval: 1m0s
  targetNamespace: tsb

