---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: book-config
  namespace: flux-system
spec:
  dependsOn:
  - name: book-install
  interval: 1m0s
  path: ./bookinfo/config
  prune: false
  sourceRef:
    kind: GitRepository
    name: deploymentrepo
  targetNamespace: bookinfo

